PRODUCT_CATALOG = [
    {
        "id": 1001,
        "category": "Smartphones",
        "brand": "Xiaomi",
        "name": "Redmi A3X",
        "price": 6999,
        "source": "Flipkart",
        "rating": 4.1,
        "review_count": 1894,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 64,
            "battery_mah": 5000,
            "camera_mp": 8,
            "display_type": "LCD",
            "refresh_rate_hz": 90,
            "fast_charge_w": 10,
            "chipset_score": 54,
            "network": "4G",
            "features": ["budget", "battery", "clean ui"]
        }
    },
    {
        "id": 1002,
        "category": "Smartphones",
        "brand": "Samsung",
        "name": "Samsung Galaxy F04",
        "price": 7499,
        "source": "Amazon",
        "rating": 4.2,
        "review_count": 3288,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 64,
            "battery_mah": 5000,
            "camera_mp": 13,
            "display_type": "LCD",
            "refresh_rate_hz": 60,
            "fast_charge_w": 15,
            "chipset_score": 58,
            "network": "4G",
            "features": ["budget", "battery", "camera"]
        }
    },
    {
        "id": 1003,
        "category": "Smartphones",
        "brand": "Motorola",
        "name": "Moto G04",
        "price": 7999,
        "source": "Flipkart",
        "rating": 4.2,
        "review_count": 1720,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 64,
            "battery_mah": 5000,
            "camera_mp": 16,
            "display_type": "LCD",
            "refresh_rate_hz": 90,
            "fast_charge_w": 15,
            "chipset_score": 60,
            "network": "4G",
            "features": ["budget", "stock android", "display"]
        }
    },
    {
        "id": 1004,
        "category": "Smartphones",
        "brand": "Lava",
        "name": "Lava Blaze 2 5G",
        "price": 9999,
        "source": "Amazon",
        "rating": 4.0,
        "review_count": 943,
        "specs": {
            "ram_gb": 6,
            "storage_gb": 128,
            "battery_mah": 5000,
            "camera_mp": 50,
            "display_type": "LCD",
            "refresh_rate_hz": 90,
            "fast_charge_w": 18,
            "chipset_score": 71,
            "network": "5G",
            "features": ["budget", "5g", "camera", "storage"]
        }
    },
    {
        "id": 1005,
        "category": "Smartphones",
        "brand": "Poco",
        "name": "Poco C65",
        "price": 8499,
        "source": "Flipkart",
        "rating": 4.1,
        "review_count": 2210,
        "specs": {
            "ram_gb": 6,
            "storage_gb": 128,
            "battery_mah": 5000,
            "camera_mp": 50,
            "display_type": "LCD",
            "refresh_rate_hz": 90,
            "fast_charge_w": 18,
            "chipset_score": 67,
            "network": "4G",
            "features": ["budget", "camera", "storage", "battery"]
        }
    },
    {
        "id": 1006,
        "category": "Smartphones",
        "brand": "Realme",
        "name": "Realme Narzo N63",
        "price": 8999,
        "source": "Amazon",
        "rating": 4.1,
        "review_count": 1577,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 64,
            "battery_mah": 5000,
            "camera_mp": 50,
            "display_type": "LCD",
            "refresh_rate_hz": 90,
            "fast_charge_w": 45,
            "chipset_score": 63,
            "network": "4G",
            "features": ["fast charging", "camera", "budget"]
        }
    },
    {
        "id": 1007,
        "category": "Smartphones",
        "brand": "Samsung",
        "name": "Samsung Galaxy M14 5G",
        "price": 12499,
        "source": "Amazon",
        "rating": 4.3,
        "review_count": 6120,
        "specs": {
            "ram_gb": 6,
            "storage_gb": 128,
            "battery_mah": 6000,
            "camera_mp": 50,
            "display_type": "LCD",
            "refresh_rate_hz": 90,
            "fast_charge_w": 25,
            "chipset_score": 74,
            "network": "5G",
            "features": ["battery", "5g", "camera"]
        }
    },
    {
        "id": 1008,
        "category": "Smartphones",
        "brand": "Redmi",
        "name": "Redmi 13C 5G",
        "price": 10999,
        "source": "Flipkart",
        "rating": 4.2,
        "review_count": 2871,
        "specs": {
            "ram_gb": 6,
            "storage_gb": 128,
            "battery_mah": 5000,
            "camera_mp": 50,
            "display_type": "LCD",
            "refresh_rate_hz": 90,
            "fast_charge_w": 18,
            "chipset_score": 72,
            "network": "5G",
            "features": ["budget", "5g", "camera", "battery"]
        }
    },
    {
        "id": 1009,
        "category": "Smartphones",
        "brand": "Nothing",
        "name": "CMF Phone 1",
        "price": 15999,
        "source": "Flipkart",
        "rating": 4.4,
        "review_count": 4033,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 128,
            "battery_mah": 5000,
            "camera_mp": 50,
            "display_type": "AMOLED",
            "refresh_rate_hz": 120,
            "fast_charge_w": 33,
            "chipset_score": 83,
            "network": "5G",
            "features": ["amoled", "performance", "design", "5g"]
        }
    },
    {
        "id": 1010,
        "category": "Smartphones",
        "brand": "Motorola",
        "name": "Moto G64 5G",
        "price": 14999,
        "source": "Flipkart",
        "rating": 4.3,
        "review_count": 2712,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 128,
            "battery_mah": 6000,
            "camera_mp": 50,
            "display_type": "LCD",
            "refresh_rate_hz": 120,
            "fast_charge_w": 33,
            "chipset_score": 82,
            "network": "5G",
            "features": ["battery", "performance", "stock android", "5g"]
        }
    },
    {
        "id": 1011,
        "category": "Laptops",
        "brand": "Jio",
        "name": "JioBook 11",
        "price": 16499,
        "source": "Amazon",
        "rating": 4.0,
        "review_count": 1204,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 64,
            "battery_mah": 4000,
            "camera_mp": 1,
            "display_type": "HD",
            "refresh_rate_hz": 60,
            "fast_charge_w": 24,
            "chipset_score": 45,
            "network": "WiFi",
            "features": ["student", "budget", "portable"]
        }
    },
    {
        "id": 1012,
        "category": "Laptops",
        "brand": "Primebook",
        "name": "Primebook 4G",
        "price": 16990,
        "source": "Flipkart",
        "rating": 4.1,
        "review_count": 890,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 128,
            "battery_mah": 4000,
            "camera_mp": 1,
            "display_type": "HD",
            "refresh_rate_hz": 60,
            "fast_charge_w": 24,
            "chipset_score": 47,
            "network": "4G",
            "features": ["student", "budget", "portable"]
        }
    },
    {
        "id": 1013,
        "category": "Laptops",
        "brand": "Infinix",
        "name": "Infinix Y1 Plus Neo",
        "price": 22990,
        "source": "Flipkart",
        "rating": 4.1,
        "review_count": 2410,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 512,
            "battery_mah": 5000,
            "camera_mp": 1,
            "display_type": "IPS",
            "refresh_rate_hz": 60,
            "fast_charge_w": 45,
            "chipset_score": 58,
            "network": "WiFi",
            "features": ["budget", "storage", "student"]
        }
    },
    {
        "id": 1014,
        "category": "Laptops",
        "brand": "Chuwi",
        "name": "Chuwi HeroBook Pro",
        "price": 23990,
        "source": "Amazon",
        "rating": 4.0,
        "review_count": 640,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 256,
            "battery_mah": 5000,
            "camera_mp": 1,
            "display_type": "IPS",
            "refresh_rate_hz": 60,
            "fast_charge_w": 36,
            "chipset_score": 55,
            "network": "WiFi",
            "features": ["budget", "display", "portable"]
        }
    },
    {
        "id": 1015,
        "category": "Laptops",
        "brand": "Lenovo",
        "name": "Lenovo V15 Celeron",
        "price": 27990,
        "source": "Amazon",
        "rating": 4.0,
        "review_count": 715,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 256,
            "battery_mah": 4200,
            "camera_mp": 1,
            "display_type": "TN",
            "refresh_rate_hz": 60,
            "fast_charge_w": 45,
            "chipset_score": 57,
            "network": "WiFi",
            "features": ["office", "budget", "student"]
        }
    },
    {
        "id": 1016,
        "category": "Laptops",
        "brand": "Acer",
        "name": "Acer Aspire Lite AL15",
        "price": 29990,
        "source": "Flipkart",
        "rating": 4.2,
        "review_count": 1880,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 512,
            "battery_mah": 4800,
            "camera_mp": 1,
            "display_type": "IPS",
            "refresh_rate_hz": 60,
            "fast_charge_w": 45,
            "chipset_score": 64,
            "network": "WiFi",
            "features": ["budget", "office", "storage"]
        }
    },
    {
        "id": 1017,
        "category": "Laptops",
        "brand": "ASUS",
        "name": "ASUS Chromebook Celeron",
        "price": 18990,
        "source": "Flipkart",
        "rating": 4.0,
        "review_count": 522,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 64,
            "battery_mah": 4200,
            "camera_mp": 1,
            "display_type": "HD",
            "refresh_rate_hz": 60,
            "fast_charge_w": 24,
            "chipset_score": 46,
            "network": "WiFi",
            "features": ["student", "budget", "battery"]
        }
    },
    {
        "id": 1018,
        "category": "Laptops",
        "brand": "HP",
        "name": "HP Chromebook 14a",
        "price": 21990,
        "source": "Amazon",
        "rating": 4.1,
        "review_count": 980,
        "specs": {
            "ram_gb": 4,
            "storage_gb": 64,
            "battery_mah": 4400,
            "camera_mp": 1,
            "display_type": "HD",
            "refresh_rate_hz": 60,
            "fast_charge_w": 45,
            "chipset_score": 48,
            "network": "WiFi",
            "features": ["student", "budget", "battery"]
        }
    },
    {
        "id": 1019,
        "category": "Laptops",
        "brand": "Avita",
        "name": "Avita Satus Ultimus",
        "price": 17990,
        "source": "Flipkart",
        "rating": 3.9,
        "review_count": 704,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 256,
            "battery_mah": 4000,
            "camera_mp": 1,
            "display_type": "FHD",
            "refresh_rate_hz": 60,
            "fast_charge_w": 24,
            "chipset_score": 50,
            "network": "WiFi",
            "features": ["budget", "display", "portable"]
        }
    },
    {
        "id": 1020,
        "category": "Laptops",
        "brand": "ZEBRONICS",
        "name": "Zebronics Pro Series Y",
        "price": 24990,
        "source": "Amazon",
        "rating": 4.0,
        "review_count": 468,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 512,
            "battery_mah": 5000,
            "camera_mp": 1,
            "display_type": "FHD",
            "refresh_rate_hz": 60,
            "fast_charge_w": 45,
            "chipset_score": 59,
            "network": "WiFi",
            "features": ["budget", "storage", "office"]
        }
    },
    {
        "id": 1011,
        "category": "Laptops",
        "brand": "Lenovo",
        "name": "Lenovo IdeaPad Slim 3",
        "price": 42990,
        "source": "Croma",
        "rating": 4.2,
        "review_count": 998,
        "specs": {
            "ram_gb": 8,
            "storage_gb": 512,
            "battery_mah": 4700,
            "camera_mp": 1,
            "display_type": "IPS",
            "refresh_rate_hz": 60,
            "fast_charge_w": 65,
            "chipset_score": 76,
            "network": "WiFi",
            "features": ["student", "battery", "office"]
        }
    },
    {
        "id": 1021,
        "category": "Laptops",
        "brand": "HP",
        "name": "HP 15 Ryzen 5",
        "price": 48990,
        "source": "Amazon",
        "rating": 4.3,
        "review_count": 1770,
        "specs": {
            "ram_gb": 16,
            "storage_gb": 512,
            "battery_mah": 4500,
            "camera_mp": 1,
            "display_type": "IPS",
            "refresh_rate_hz": 60,
            "fast_charge_w": 65,
            "chipset_score": 81,
            "network": "WiFi",
            "features": ["performance", "office", "coding"]
        }
    },
    {
        "id": 1022,
        "category": "Laptops",
        "brand": "ASUS",
        "name": "ASUS Vivobook 16X",
        "price": 57990,
        "source": "Flipkart",
        "rating": 4.4,
        "review_count": 830,
        "specs": {
            "ram_gb": 16,
            "storage_gb": 512,
            "battery_mah": 5000,
            "camera_mp": 1,
            "display_type": "IPS",
            "refresh_rate_hz": 120,
            "fast_charge_w": 90,
            "chipset_score": 86,
            "network": "WiFi",
            "features": ["creator", "performance", "display"]
        }
    },
    {
        "id": 1023,
        "category": "Audio",
        "brand": "OnePlus",
        "name": "OnePlus Nord Buds 2r",
        "price": 1799,
        "source": "Amazon",
        "rating": 4.1,
        "review_count": 9021,
        "specs": {
            "ram_gb": 0,
            "storage_gb": 0,
            "battery_mah": 480,
            "camera_mp": 0,
            "display_type": "NA",
            "refresh_rate_hz": 0,
            "fast_charge_w": 10,
            "chipset_score": 60,
            "network": "Bluetooth",
            "features": ["budget", "bass", "battery"]
        }
    },
    {
        "id": 1024,
        "category": "Audio",
        "brand": "Realme",
        "name": "Realme Buds Air 6",
        "price": 2999,
        "source": "Flipkart",
        "rating": 4.2,
        "review_count": 4008,
        "specs": {
            "ram_gb": 0,
            "storage_gb": 0,
            "battery_mah": 520,
            "camera_mp": 0,
            "display_type": "NA",
            "refresh_rate_hz": 0,
            "fast_charge_w": 15,
            "chipset_score": 68,
            "network": "Bluetooth",
            "features": ["anc", "battery", "call quality"]
        }
    }
]
